### ISSUE TITLE
Auxiliary functions

### ISSUE THREAD

**Issue by Pakillo** [EcologyR/mappestRisk#15]
Move them to R folder
Clean the script (e.g. library calls, rm, etc)
Revise the functions, possibly test the most important
Some of them should probably be documented? (eg. devmodels)

**Comment by dario-ssm** [comment]
For tomorrow, still undone with `auxiliary_functions_devmodels.R`:

- [ ] Test some functions (I've annotatedd which ones to test)
- [ ] Document equations and `start_vals_devrate()`: think the most efficient way to do it

**Comment by dario-ssm** [comment]
Finished test and short documentation (since it won't be an available function for the user)
