### ISSUE TITLE
Fix the query on pixels of the interactive map

### ISSUE THREAD

**Issue by ajpelu** [EcologyR/mappestRisk#30]
Using terra, the addImageQuery of the leaflem pkg doesn't work. We comment the following lines:
https://github.com/EcologyR/mappestRisk/blob/c415bd44888007593fa59c8dd265ef1dbb03ea33/R/interactive_map.R#L69-L74

ToDo: Ask to leaflem developers (https://r-spatial.github.io/leafem/).

**Comment by ajpelu** [comment]
Temporal solution. 
- At the top of the function we add a transformation from terra to raster. Then the addImageQuery works.

**Comment by ajpelu** [comment]
We need to fix this in near future when leafem  and leaflet include the changes of terra.

**Comment by dario-ssm** [comment]
I'm closing this issue as the function is no longer active. Might be useful in a future enhancement to customize the interactive map plotter.
