### ISSUE TITLE
map_risk(): fix extent overlap error

### ISSUE THREAD

**Issue by AMBarbosa** [EcologyR/mappestRisk#34]
sometimes there's an unjustified error about extents not overlapping between `region` and `t_rast`

**Comment by ajpelu** [comment]
Hi @AMBarbosa. Yes, after git pull, It works. Test: 

```
tavg_file <- system.file("extdata/tavg_lux.tif", package = "mappestRisk")
tavg_rast <- terra::rast(tavg_file)
risk_rast_binary <- map_risk(t_vals = c(12.5, 21.4), t_rast = tavg_rast)
interactive_map(risk_rast_binary[[13]])
```
It works ok. No errors. No messages. No warnings.

Thanks!! Good work @AMBarbosa
