### ISSUE TITLE
Problems with interactive_map() example

### ISSUE THREAD

**Issue by dario-ssm** [EcologyR/mappestRisk#40]
I have tried the example in `interactive_map()` and it returns me an error:
`Error in raster::projectRaster(x, raster::projectExtent(x, crs = sp::CRS(epsg3857)), :
input projection is NA` 

I tried uncommenting possible fixes in the function, with no result, do you have an idea on how to make it work @ajpelu ?
In addition, I have generated a complete example, so the raster to load now for this example might better be `/inst/extdata/risk_rast-tif`, which comes from `map_risk()` function applied to Réunion island instead of Luxembourg (since it combines both a steep altitudinal gradient and hot temperatures required to the example species that Luxembourg did not accomplished).

**Comment by AMBarbosa** [comment]
I've installed mappestRisk, tried the interactive_map() example with both rasters and it works for me. What code did you use exactly? And are you using the latest version of the function? The code in the error message does not appear in the interactive_map() function.

**Comment by dario-ssm** [comment]
Thank you Marcia! I've just updated RStudio version and manually un-installed and reinstalled a bunch of package-dependencies from `terra `and `rstudio/leaflet` and now it works perfectly using the following code:

`r <- terra::rast("inst/extdata/risk_rast.tif")[[13]]`

`interactive_map(x = r, map_type = "high",  
                           path_out = paste0(tempdir(), "test_map.html"))
`

Maybe we should add some note suggesting possible users to update RStudio and ensure updating all dependencies of terra and rstudio/leaflet?
