### ISSUE TITLE
On README.md

### ISSUE THREAD

**Issue by dario-ssm** [EcologyR/mappestRisk#42]
I have updated some things of the general workflow in teh example for the README.
I think we should minimise the code for the example to _just_ work and expand it in a future vignette (I can assign myself @dario-ssm  to that).

I changed some part of the example of `map_risk` (just in the README, not in the function) to extract data into Réunion Island, with a steep gradient of elevations and more subtropical, hot temperatures --since the `tvals` obtained for the example are too high for Luxembourg even in summer.

The description of both sections 4 and 5 of the examples (the corresponding functions of @AMBarbosa and @ajpelu) are empty by now, so if you have some time to complete them, that would be perfect!

**Comment by AMBarbosa** [comment]
I've added my section and submitted a pull request. Haven't merged it myself, as I've also made some minor edits to your sections of the text, pending your approval.
