### ISSUE TITLE
plot_uncertainties() undocumented dependency

### ISSUE THREAD

**Issue by AMBarbosa** [EcologyR/mappestRisk#49]
When running the `plot_uncertainties()` function as in the README file, I get `Error in loadNamespace(x) : there is no package called ‘ggthemes’`, so maybe `ggthemes` should be added to the dependencies?

**Comment by dario-ssm** [comment]
I will check it out as soon as `predict_curves()` is debugged. However, I'd rather change it to a `ggplot2` theme to avoid an extra dependency for this thing.

Thanks for pointing it out!

**Comment by dario-ssm** [comment]
I have changed it to `ggplot2::theme_bw()` to avoid the additional dependency and to be consistent with the theme in `plot_devmodels()`
