### ISSUE TITLE
Translate into terra-like code

### ISSUE THREAD

**Issue by dario-ssm** [EcologyR/mappestRisk#5]
El archivo se llama spatial_functions.R
@AMBarbosa

**Comment by AMBarbosa** [comment]
- [ ] replace all spatial functions by 'terra' functions
- [ ] convert script to function
- [ ] define arguments and default values
- [ ] add and edit roxygen skeleton
- [ ] add code for future projection

**Comment by dario-ssm** [comment]
Hola @AMBarbosa, quería preguntarte cómo guardaste el archivo .RData para cargar los `country_names` alojados en la carpeta _Data_; he intentado hacer lo mismo para los nombres `model_names` en un archivo _list_available_names_ pero me da el siguiente error al usar `data(list_available_names)`

`bad restore file magic number (file may be corrupted) -- no data loaded`

Gracias!

**Comment by AMBarbosa** [comment]
El `data()` también me daba error, aunque no recuerdo el mensaje exactamente. Pero pregunté a Paco y dijo (si lo recuerdo bien) que dentro del paquete no tenía que hacer `data(country_names)`, sino llamar directamente `country_names`.

**Comment by Pakillo** [comment]
Hola

En efecto, dentro de las funciones no hace falta usar data(), simplemente usar el nombre del dataset.

Para que `data(list_available_names)` tienes que instalar tu paquete o usar Build -> Load all, si no el dataset no está accesible. Creo que puede ser eso. Prueba a ver
