### ISSUE TITLE
#work on raster visualization

### ISSUE THREAD

**Issue by dario-ssm** [EcologyR/mappestRisk#6]

**Comment by ajpelu** [comment]
Objetivos de la función: 

- A partir de un raster (mapa de riesgo) generar un mapa dinámico y un mapa estático

## Cuestiones a considerar 
- Partimos de un raster llamado `species_suitability_XXXX_riskmap.tiff` siendo `species` el nombre la especie, y `XXXX` high o medium. *eg* `pierisrapae_suitability_high_riskmap.tiff`
- Ofrecer al usuario la opción de exportar el mapa estático
- Generar un leaflet dinámico que se abra en un navegador

**Comment by ajpelu** [comment]
@dario-ssm necesitaría un raster real de los que queramos generar el mapa dinámico. Por fa, súbelo, por si estos días de Semana Santa puedo dedicar un tiempo a avanzar con el código. 
Gracias

**Comment by dario-ssm** [comment]
Hola Antonio!
Estupendo, hoy dejo trabajando el ordenador para generarlo y te lo envío a la tarde o mañana en un momentillo, que tuve problemas con mi rama y tengo que volver a empezarla :/
Gracias!

**Comment by AMBarbosa** [comment]
@ajpelu También puedes probar a obtener rasters con el código abajo (de los ejemplos en 'map_risk.R'). Serán el tipo de mapas que el usuario obtendrá con el paquete, y que luego pasará a tu función. Pero de momento la función 'map_risk.R' está sacando simplemente rasters con las temperaturas en los sitios que estén dentro de los límites de la zona óptima; no están ni binarizados ni reescalados según cuán cerca están del óptimo.

```
# the function and data below will be loaded automatically once the package can be installed, but for now we can source them from GitHub:
source("https://raw.githubusercontent.com/EcologyR/mappestRisk/main/R/map_risk.R")
download.file("https://github.com/EcologyR/mappestRisk/raw/main/data/country_names.rda", "country_names.rda")
load("country_names.rda")

# get a set of risk rasters:
risk_rasters <- map_risk(t_vals = c(12.5, 21.4), region = c("Portugal", "Spain"))

# plot them:
terra::plot(risk_rasters)  # monthly rasters + mean
terra::plot(risk_rasters[["mean"]])

# save to file (if needed):
terra::writeRaster(risk_rasters[["mean"]], "risk_mean.tif")
```

**Comment by ajpelu** [comment]
Gracias a ambos. 
@dario-ssm no te preocupes. en cuanto puedas. 
Gracias @AMBarbosa, sí, ya tengo un raster de temperaturas, pero necesito uno real de número de meses para cuadrar mejor las leyendas. No obstante gracias. Por cierto, está genial la función map_risk!! Enhorabuena

Finalmente, tenemos que ir pensando en un logo chulo!!

**Comment by dario-ssm** [comment]
Aquí tienes

> Gracias a ambos. @dario-ssm no te preocupes. en cuanto puedas. Gracias @AMBarbosa, sí, ya tengo un raster de temperaturas, pero necesito uno real de número de meses para cuadrar mejor las leyendas. No obstante gracias. Por cierto, está genial la función map_risk!! Enhorabuena
> 
> Finalmente, tenemos que ir pensando en un logo chulo!!

Aquí tienes @ajpelu  (commit: 42f851236ef565ecc45904eaae7b4debeb5c86cd ). Le daré vueltas a lo del logo :)
Es genial la función de @AMBarbosa, espero que pronto podamos implementarla con la que estoy escribiendo yo binarizada y aproximada a los óptimos; aún me llevará tiempo.

Saludos y feliz semana santa.

**Comment by ajpelu** [comment]
First draft of plot_map uploaded. See commit 1f2c64cd8068bf6844cbde4d6714ebd091270427
