### ISSUE TITLE
Error in test-auxiliary_functions_modelfitting

### ISSUE THREAD

**Issue by ajpelu** [EcologyR/mappestRisk#63]
I'm trying to install the pkg to run some of the functions, to assess the suitability of interactive_map, but I cannot install the pkg as I found an error in test-auxiliary_functions_modelfitting.R, specifically: 

```
Error ('test-auxiliary_functions_modelfitting.R:7:3'): start_vals_devRate should throw an error if temperature data is not numeric ──
Error in `eval(code, test_env)`: object 'dev_model_table' not found
```

It seems `dev_model_table` is not found on the pkg.

**Comment by dario-ssm** [comment]
This happens because the meeting day we changed `dev_model_table` name to `available_models`.  It seems that auxiliary functions script was not changed, so I will change it ASAP
